project_id = "dqebigulyemxctgrpftf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "analyze-questionnaire"
verify_jwt = true

[[functions]]
name = "import-sni-codes"
verify_jwt = true