// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://dqebigulyemxctgrpftf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxZWJpZ3VseWVteGN0Z3JwZnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyNzEyMzEsImV4cCI6MjA0Nzg0NzIzMX0.iuaz3RAZbvGa5TVfCihPk3aK90oSIczi287fklyhh7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);